### ISSUE TITLE
EPSR Manager Module

### ISSUE THREAD

**Issue by Danbr4d** [trisyoungs/duq#1756]
### Focus
Implementation of a new EPSR Manager module to give users more control over the functionality of EPSR.

### Tasks
- [ ] Allow blending of partials across multiple EPSR modules
- [ ] Restrict potential generation to those involving specific atom types
- [ ] Prevent potential generation for specific atom type pairs

Added in #1755
