### ISSUE TITLE
[Epic] Refactor Analysis Modules

### ISSUE THREAD

**Issue by trisyoungs** [trisyoungs/duq#1769]
### Focus
Highlighted and described in #1747, this Epic encapsulates all necessary work related to moving our existing analysis modules from the old `Procedure`/`ProcedureNode`-based system onto a more developer-friendly footing.

### Tasks (Modules)
- [x] Convert `angle` Module
- [x] ~Convert `avgMol` Module~
- [x] Convert `axisAngle` Module
- [x] Convert `dAngle` Module
- [x] Convert `histogramCN` Module
- [x] Convert `intraAngle` Module
- [x] Convert `intraDistance` Module
- [x] Convert `orientedSDF` Module
- [x] Convert `sdf` Module
- [x] Convert `siteRDF` Module

### Knock-on Effects
Once complete the following issues are potentially redundant.
- [x] #1648
- [ ] #1600 (Hooray!)
- [x] #1503
- [x] #1459

**Comment by jws-1** [comment]
`avgMol` doesn't actually utilise the `Procedure` framework - is there some other refactoring that you had in mind regarding it?

**Comment by trisyoungs** [comment]
TBH it's probably due a refactor, but since it's not based off the `Procedure` stuff I think we can leave it be for now.

**Comment by trisyoungs** [comment]
Closed by #1789 and #1795.
