### ISSUE TITLE
Handle deprecations in TOML backwards compatibility

### ISSUE THREAD

**Issue by trisyoungs** [trisyoungs/duq#1831]
**Describe the feature / issue**
In preparation for moving to TOML there are several input parameters in the existing format which are new or slated as deprecated (but we still read them for now). These should have proper backwards compatibility adapters implemented to handle conversion of older input files when we move to TOML as the standard.

When deprecations or new input keywords are added to the current txt file format they should be captured here.

## TODO
- [ ] `Override` keyword (introduced in 1.5 by #1826)
- [ ] `ShortRangeTruncationWidth` keyword  in "PairPotentials" input block (deprecated by #1826)
- [ ] `SizeFactor` keyword in `Configuration` block (now a `ProcedureNode`)
- [ ] `Temperature` keyword in `Configuration` block (now a `ProcedureNode`)
- [ ] `UseHalfCellRange` keyword in `GRModule`
- [ ] `VariableTimestep` keyword in `MDModule`
