### ISSUE TITLE
Epic / Keyword Modernisation

### ISSUE THREAD

**Issue by trisyoungs** [trisyoungs/duq#827]
### Focus
Modernise keyword-related classes, and remove them from `List` as part of #257. This issue keeps track of a draft PR stack / work in progress, briefly stating the significant changes in each PR.

### 1. Simplify Data Storage
Branch: [`new-keywords-1`](https://github.com/disorderedmaterials/dissolve/tree/new-keywords-1)
- [x] Temporarily move to `std::vector` of pointers over `List` in `KeywordList`
- [x] Move all keywords to store data within keyword, rather than references
- [x] Update `KeywordList` retrieval functions to permit changes.

### 2. Local Variables
Branch: [`new-keywords-2`](https://github.com/disorderedmaterials/dissolve/tree/new-keywords-2)
- [x] Remove inconsistent `arguments_` storage for keywords
- [x] Rework `KeywordList` to store base class ref and derived class `typeid`
- [x] Move POD keywords to be local class members, and add them to managing class
- [x] Move class-based keywords to be local class members, and add them to managing class
- [x] Move STL-based keywords to be local class members, and add them to managing class
- [x] Remove `LinkToKeyword` class since this is no longer necessary?
- [x] Make `KeywordBase::set_` private (?) and remove derived-class `setData`/`setValue` members in favour of non-const return of `data_`.
- [x] Remove need for `KeywordXXX` -> `KeywordData` -> `KeywordBase` class hierarchy
- [x] Remove `asInt()`, `asDouble()` etc. functions (no longer necessary once move to local members)
- [x] Better setting of `optionMask` on `KeywordInfo` - separate function in `KeywordList`?

### 3. Remove Type, Move To Widget Producers
Branch: [`new-keywords-3`](https://github.com/disorderedmaterials/dissolve/tree/new-keywords-3)
- [x] Remove `KeywordData::type_` enum
- [x] Clearly separate keywords from widgets via producer-style class
- [x] Take derived class keyword pointers in widget constructors.

### 4. Tidy
Branch: [`new-keywords-4`](https://github.com/disorderedmaterials/dissolve/tree/new-keywords-4)
- [x] Rename `read` and `write` to `serialise` and `deserialise` for consistency.
- [x] ~Rename module `init.cpp` for `control.cpp` to be more descriptive and consistent~
- [x] Rename `KeywordList` to `KeywordStore`.
- [x] Store `allKeywords_` in `KeywordStore` as opposed to `KeywordBase`, and move to `std::vector` (from `RefList`)
- [x] Rename horrible slots (`my*`)
- [x] Use `std::optional` for argument range specifcation

### Rejected
- [x] ~Remove `set_`, `hasBeenSet()` etc. in favour of using keywords based on `std::optional`?~
- [x] ~Remove explicit template parameter from `add()` calls and move to producer-style mapping~
- [x] ~Move keywords to be local member variables and store in `std::variant`~
- [x] ~Calculate_* modules typically store Vec3<double> ranges just to set in nodes - can just target node variables instead and apply suitable limits at keyword creation time.~

### Related Issues
#612 
#556 
#403
#779
#36 

### Follow-On Issues to Submit
- Add model for Configuration and rework `ConfigurationVectorKeywordWidget`
- Add model for Module and rework `ModuleVectorKeywordWidget`
- Add model for Species and rework `SpeciesKeywordWIdget` and `SpeciesVectorKeywordWidget`
- Ensure we have consistency in `NeutronSQModule::calculateWeights` (narrowing from `double` to `int`)
- Reorganise module files - don't enforce `core.cpp`, `init.cpp` etc., since it's a bit pointless. Just have one named after the module (as with the header) and a separate `process.cpp` and `functions.cpp` , and possibly `control.cpp` as necessary.
